# .scrutinizer.yml

build:
  environment:
    php: 7.2.8
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - php-scrutinizer-run
        - command: phpcs-run
          - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
            coverage:
              file: './build/coverage/index.xml'
              format: 'clover'
              - 'vendor/bin/grumphp run --no-interaction'